dubbo.application.id: ${spring.application.name}
dubbo.application.name: ${spring.application.name}
# 禁用QOS同一台机器可能会有端口冲突现象
dubbo.application.qos-enable: false
dubbo.application.qos-accept-foreign-ip: false
# 配置注册中心
dubbo.registry.address: nacos://${spring.cloud.nacos.discovery.server-addr}
dubbo.registry.register: false

dubbo.protocol.id: dubbo
dubbo.protocol.name: dubbo
dubbo.protocol.port: 20882
